// <auto-generated />
using IRunes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IRunes.Data.Migrations
{
    [DbContext(typeof(IRunesDbContext))]
    [Migration("20181007101146_Update_1.0")]
    partial class Update_10
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IRunes.Models.Album", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cover");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(30)")
                        .HasAnnotation("[StringLength(30, MinimumLength = 3, ErrorMessage = \"Invalid\")]", true);

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("IRunes.Models.AlbumTrack", b =>
                {
                    b.Property<string>("TrackId");

                    b.Property<string>("AlbumId");

                    b.Property<string>("Id");

                    b.HasKey("TrackId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("AlbumTracks");
                });

            modelBuilder.Entity("IRunes.Models.Track", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Link")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(30)")
                        .HasAnnotation("[StringLength(30, MinimumLength = 3, ErrorMessage = \"Invalid\")]", true);

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("IRunes.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(30)")
                        .HasAnnotation("[StringLength(30, MinimumLength = 3, ErrorMessage = \"Invalid\")]", true);

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Username")
                        .HasColumnType("VARCHAR(30)")
                        .HasAnnotation("[StringLength(30, MinimumLength = 3, ErrorMessage = \"Invalid\")]", true);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IRunes.Models.Album", b =>
                {
                    b.HasOne("IRunes.Models.User", "User")
                        .WithMany("Albums")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IRunes.Models.AlbumTrack", b =>
                {
                    b.HasOne("IRunes.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IRunes.Models.Track", "Track")
                        .WithMany("Albums")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
